Add Engine .shutdown() expected interface (#1302)
Commit 8effb2a1b56397ae4e6873aa1f67ce51ccf9adaf assumed an interface for
`EngineBase.shutdown()` that accepted `block` as an argument.  Unfortunately,
not all engines implement this keyword; those using the `GlobusComputeEngine`
would receive a traceback after shutdown (during cleanup) like:

    Traceback (most recent call last):
      File "VENVBIN/bin/globus-compute-endpoint", line 33, in <module>
        sys.exit(load_entry_point('globus-compute-endpoint', 'console_scripts', 'globus-compute-endpoint')())
      ...
      File "VENV/globus_compute_endpoint/endpoint/interchange.py", line 302, in start
        self.cleanup()
      File "VENV/globus_compute_endpoint/endpoint/interchange.py", line 206, in cleanup
        self.executor.shutdown(block=True)
    TypeError: GlobusComputeEngine.shutdown() got an unexpected keyword argument 'block'

Address that by teaching the `GlobusComputeEngineBase` what is an acceptable
interface for the `.shutdown()` method, and then honoring that interface in the
subclasses.