Upping the websocket message size limit of from 1MB to 11MB. (#678)
* Upping the websocket message size limit of from 1MB to 11MB.

Size updated from 1048576 -> 11534336, 1MB allowance for wrappers and such.
With the existing limits larger results are dropped by the websockets with
exception: websockets.exceptions.PayloadTooBig

* Adding changelog fragment